bar/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls), 
    path("",include ("barApp.urls") ), 
    path("", include("login.urls")),
    path("", include("ventas.urls")),
    path("", include("pedidos.urls")), 
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ventas/urls.py
from django.urls import path 
from .import views


app_name = "carro" 

urlpatterns = [
    path("registro_venta/", views.registro_venta, name="registro"),
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),    
    path("ventas/", views.ventas, name="ventas"),
]

ventas/models.py
from django.db import models
from barApp.models import Producto, Trabajador
from django.contrib.auth import get_user_model
from django.db.models import F, Sum, FloatField

# Create your models here.


User= get_user_model()

class Venta (models.Model):
    
    trabajador= models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    fecha= models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = ("Venta")
        verbose_name_plural =("Ventas")

    def __str__(self):
        return self.name
    
    @property
    def total(self):
        return self.Ventas_Producto_set.aggregate(
            total=Sum(F("precio")*F("cantidad"), output_field=FloatField())
        )['total'] or FloatField(0)
    
   


class Ventas_Producto(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    id_venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    cantidad = models.IntegerField("Cantidad")
    fecha= models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Ventas_Producto")
        verbose_name_plural =("Ventas_Productos")

    def __str__(self):
        return f'{self.cantidad} unidades de {self.id_producto.nombre_P}'

ventas/views.py
from django.shortcuts import render
from .carro import Carro
from ventas.models import Producto
from django.shortcuts import redirect
from pedidos.models import LineaPedido




# Create your views here.
def registro_venta(request):   
     
     producto=Producto.objects.all()
    
     return render(request, "registro_venta.html", {"productos":producto})    
    
def agregar_producto(request, producto_id):
     carro=Carro(request)
     
     producto=Producto.objects.get(id=producto_id)
     
     carro.agregar(producto=producto)
     pass
     return redirect('producto')
 
 
def eliminar_producto(request, producto_id):
     carro=Carro(request)
     
     producto=Producto.objects.get(id=producto_id)
     
     carro.eliminar(producto=producto)
     
     return redirect('carro:registro')
 
 

def restar_producto(request, producto_id):
     carro=Carro(request)
     
     producto=Producto.objects.get(id=producto_id)
     
     carro.restar_producto(producto=producto)
     
     return redirect('carro:registro')
 

def limpiar_carro(request, producto_id):
     carro=Carro(request)
     
     carro.limpiar_carro()
     
     return redirect('carro:registro')

def ventas(request):
     venta= LineaPedido.objects.all()
     
     return render(request, 'ventas.html', {'ventas':venta})

ventas/templates/registro_venta.html
{% extends 'body.html' %}
{% block title %}Ventas{% endblock title %}
{% block content %}

<div class="container" style="height:90vh"> "
<table class="table table-bordered" style="color: white;">

    <thead> 
        <tr>
            <th colspan="3" class="text-center">
                Carro de compras
            </th>
        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>

        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}

            {% for key, value in request.session.carro.items %}

              <tr class="text-center">

                <td>{{value.nombre}}</td>
                <td>{{value.cantidad}}</td>
                <td>

                    <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                    <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                    <br/>

                    {{value.precio}} €

                </td>

              </tr>  
            {% endfor %}

            {% else %}

            <tr>

                <td colspan="3">
                    <div class="alert alert-danger text-center">

                        Sin productos
                    </div>
                </td>


            </tr>



            {% endif %}
    </tbody>

    <tfoot>

        <tr>

            <td colspan="3">

                Total: {{importe_total_carro}} $

            </td>

        </tr>
        {% if request.session.carro.items %}
        <tr><td colspan="3" style="text-align: center;">

            <a href="../pedidos" class="btn btn-success">Registrar venta</a>

        </td></tr>
        {% endif %}

    </tfoot>

</table>
</tbody>

</div>
 {% endblock content %}

ventas/templates/ventas.html
{% extends 'body.html' %}
{% block title %}
Reportes ventas 
{% endblock %}
{% block content %}
<div class=" mx-5">
    <h2 class="text-center pt-4" style="color:white; font-family:san-serif">Reporte de las ventas</h2>
    <table class="border border-dark bg-secondary">
        <thead>
            <colgroup>
                <col style="width: 10%"/>
                <col style="width: 20%"/>
                <col style="width: 20%"/>
                <col style="width: 10%"/> 
                <col style="width: 10%"/>
                <col style="width: 30%"/>
                <col style="width: 10%"/>                        
            </colgroup>  
        </thead>
        <tbody class="">
            <tr class="border border-dark text-center">
                <td class="text-center">Vendedor</td>
                <td>Producto</td>
                <td>Venta Nro. </td>
                <td>Cantidad</td>
                <td>Fecha venta</td>
                <td>Precio total</td>
            </tr>
            {% for v in ventas %}            
            
            <tr class="text-center">
            <td>{{v.user}}</td>
            <td>{{v.producto.nombre_P}}</td>
            <td>{{v.pedido}}</td>
            <td>{{v.cantidad}}</td>
            <td>{{v.created_at}}</td> 
            <td>{{v.total}}</td> 
                        
            {% endfor %}
        </tr>
                        
        </tbody>
    </table>    
</div>

{% endblock content %}