bar/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls), 
    path("",include ("barApp.urls") ), 
    path("", include("login.urls")),
    path("", include("ventas.urls")),
    path("", include("pedidos.urls")), 
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

barApp/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path("", views.index, name="inicio"),
    path("eventos/", views.eventos, name="eventos"),
    path("hot/", views.hot, name="hot"),
    path("cold/", views.cold, name="cold"),
    path("food/", views.food, name="food"),
    path("producto/", views.producto, name="producto"),
    path("nosotros/", views.nosotros, name="nosotros"),
    path("contacto/", views.contacto, name="contacto"),
    path("cafe/", views.cafe,name="cafe"),
    path("galeria/", views.galeria, name="galeria"),
] 

ventas/urls.py
from django.urls import path 
from .import views


app_name = "carro" 

urlpatterns = [
    path("registro_venta/", views.registro_venta, name="registro"),
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),    
    path("ventas/", views.ventas, name="ventas"),
]

barApp/models.py
from datetime import datetime
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class Trabajador (models.Model):
    nom_T = models.CharField("Nombre",max_length=45)
    apellido_T = models.CharField("Apellido",max_length=45)
    direccion_T = models.CharField("Dirección",max_length=45)
    telefono_T = models.CharField("Teléfono", max_length=45)
    email= models.CharField("Correo electrónico", max_length=45)
    
    class Meta:
        verbose_name_plural = "Trabajadores"
        
    def __str__(self):
        return "%s %s" %(self.nom_T, self.apellido_T)
    
class Factura (models.Model):
    fecha_F = models.DateField("Fecha factura",auto_now=False, auto_now_add=False)    
    id_T = models.ForeignKey(Trabajador, on_delete=models.CASCADE, verbose_name="Trabajadores")
    
    class Meta:
        verbose_name_plural = "Facturas"
    
    def __str2__(self):
        
        return "%s" (self.fecha_F)
    
class Producto (models.Model):
    
    CATEGORIA_PRODUCTOS=[
        ("hot", "Bebidas calientes"),
        ("cold", "Bebidas frías"),
        ("food", "Alimentos"),
    ]
    nombre_P = models.CharField( "Nombre del producto",max_length=45)
    categoria_P= models.CharField( "Categoria del producto", max_length=45 , choices=CATEGORIA_PRODUCTOS)
    descripcion_P = models.CharField( "Descripción del producto",max_length=200)
    cantidad_P = models.IntegerField("Cantidad del producto",)
    precio_P = models.IntegerField("Precio del producto",)
    imagen_P = models.ImageField("Imagen del producto", upload_to="static/imagenes/DB")
    
    def __str__(self):
        return "Nombre: %s Cantidad: %s Precio: %s" % (self.nombre_P, self.cantidad_P, self.precio_P)
    
class Factura_Producto(models.Model):
    cod_F = models.ForeignKey(Factura, on_delete=models.CASCADE, verbose_name="Código Factura")
    cod_P = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Código Producto")
    
class Proveedor(models.Model):
    nom_Pr = models.CharField("Nombre del proveedor", max_length=45)
    direccion_Pr = models.CharField("Dirección del proveedor", max_length=45)
    telefono_Pr = models.CharField( "Teléfono del proveedor",max_length=45)
    correo_Pr = models.EmailField("Correo electrónico", max_length=254)
    
    class Meta:
        verbose_name_plural= "Proveedores"
        
    def __str__(self):
        return "Proveedor: %s" % self.nom_Pr 
    
class Producto_Proveedor(models.Model):
    cod_P = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Código Producto")
    id_Pr = models.ForeignKey(Proveedor, on_delete=models.CASCADE, verbose_name="Código Proveedor")
    
    class Meta:
        verbose_name_plural="Producto_Proveedores"
        

opciones_consultas = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]
]

        
class Contacto (models.Model):
    nombre= models.CharField(max_length=45)
    email= models.EmailField()
    tipo_consulta= models.IntegerField(choices=opciones_consultas)
    mensaje= models.TextField()
    
    def __str__(self):
        return self.nombre
            

barApp/forms.py
from django import forms
from .models import Contacto

class ContactForm(forms.ModelForm):
    
    class Meta:
        model = Contacto
        #fields = ('nombre', 'email', 'tipo_consulta', 'mensaje')
        fields = '__all__'

barApp/views.py
from django.shortcuts import render
from .models import Producto
from .forms import ContactForm

# Create your views here.
def index(request):
    return render(request,'inicio.html')

def eventos(request):
    return render(request,'eventos.html')

def hot(request):
    
    productos= Producto.objects.filter(categoria_P="hot")
    
    return render(request,'hot.html', {"productos": productos})

def cold(request):
    
    productos= Producto.objects.filter(categoria_P="cold")
    
    return render(request,'cold.html', {"productos": productos})

def food(request):
    
    productos=Producto.objects.filter(categoria_P="food")
    
    return render(request,'food.html', {"productos": productos})

def producto(request):
    
    product_cold=Producto.objects.filter(categoria_P="cold") [:3]
    product_hot=Producto.objects.filter(categoria_P="hot")[:3]
    product_food=Producto.objects.filter(categoria_P="food") [:3]
    
    
    return render(request,'producto.html', {"product_cold": product_cold, "product_food": product_food, "product_hot": product_hot})
    

def nosotros(request):
    
    return render(request, 'nosotros.html')


def contacto (request):
    data = {
        'form': ContactForm()
    }
    
    if request.method == 'POST':
        formulario = ContactForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "Contacto enviado!"
            
        else:
            data["form"] = formulario
            
    return render(request, 'contacto.html', data)

def cafe (request):
    return render(request, 'cafe.html')


def galeria(request):
    
    return render(request, 'galeria.html')

barApp/templates/body.html
{% load bootstrap5 %}
{% load static %}
{%bootstrap_css %}
{%bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            overflow: hidden;
        }
        body{
            background-image: url("{% static "cafe-10.jpg"%}");
            background-attachment: fixed;
            background-size:cover;
            overflow:scroll;
        }
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <title>
        {% block title %}{% endblock  %}
    </title>
</head>
<body>
    
<nav class="navbar navbar-expand-sm navbar-dark  " style="background-color:  #311c19" >
    <div class="container p-2">
      <a class="navbar-brand fs-4" href="{% url 'inicio' %}">Oh la lá</a>
      <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
              <li class="nav-item p-2">
                  <a class="nav-link active" href="{% url "inicio"  %}" aria-current="page">Inicio <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item dropdown p-2" >
                  <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Productos</a>
                  <div class="dropdown-menu" aria-labelledby="dropdownId">
                      <a class="dropdown-item" href="{% url "producto" %}">Productos</a>
                      <a class="dropdown-item" href="{% url "hot" %}">Bebidas calientes</a>
                      <a class="dropdown-item" href="{% url "cold" %}">Bebidas frías</a>
                      <a class="dropdown-item" href="{% url "food" %}">Alimentos</a>
                  </div>
              </li>
              <li class="nav-item dropdown p-2" >
                <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Eventos</a>
                <div class="dropdown-menu" aria-labelledby="dropdownId">
                    <a class="dropdown-item" href="{% url "eventos" %}">Eventos</a>
                    <a class="dropdown-item" href="{% url "producto" %}">Novedades</a>
              <li class="nav-item p-2">
                  <a class="nav-link" href="{% url "galeria" %}">Galería</a>
              </li>
              <li class="nav-item p-2">
                  <a class="nav-link" href="{% url "contacto" %}">Contacto</a>
              </li> 
              <li class="nav-item p-2">
                <a class="nav-link" href="{% url "register" %}">Registrarse</a>
            </li>
            
                {% if request.user.is_authenticated%}
                <li class="nav-item p-2">    
                <a style="color:white" class="nav-link"  href="{% url 'logout' %}">Cerrar sesión</a>
                </li>
                <li class="nav-item p-2">
                <a style="color:white" href="{% url "carro:ventas" %}" class="nav-link" >Bienvenid@{{user.username}}</a>
                </li>
               {% else %}
               <li class="nav-item p-2">
               <a style="color:white" class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>               
               </li>
               {% endif %}
            </li>                                
          </ul>            
      </div>
</div>
</nav>



{% block content %}{% endblock  %}

<footer class=" pt-4"  style=" background-color:   #311c19">
    <div class="container">
        <p class="text-center" style="background-color: #311c19; color:white">
            Copyright @Danna
        </p>
        <div class="row ">
            <div class= "col-4">
               <a href="{% url "nosotros"%}"> <p class="text-center text-secondary" >Sobre nosotros </p> </a>
               <a href=" {% url "contacto"%}" ><p class="text-center text-secondary">Contáctanos </p> </a>
            </div>
            <div class= "col-4">
                <a href="{% url "cafe" %}" ><p class="text-center text-secondary"> Preparación del café </p> </a>
                <a href="" > <p class="text-center text-secondary"> Ayuda</p> </a>
            </div>
        </div> 
    </div>
</footer>
{% if request.user.is_authenticated%}
<div style="position:fixed; z-index:100; left:30px; bottom:30px">
    <a href="{% url 'carro:registro' %}"><img src="{% static 'imagenes/cart2.svg' %}" style="     " width=100px></a>
</div>
{% endif%}
</body>
</html>

barApp/templates/cafe.html
{% extends 'body.html' %}
{% load static %}
{% block title %}Preparación del café{% endblock title %}
{% block content %}


<div class="row">
         
<div style="position:absolute; padding-top:5em; width:34%; left:33%; top:50%; z-index:100; font-family:san-serif">

    <h2 style="color:white; text-align:center; font-size:3.5em">Los procesos del café</h2>
  
  </div>  
    <div  class="mx-auto w-100 "class="col-12" style="padding-top:1em; width:100%; left:100%; top:50% ">
        <img src=" {% static "imagenes/plantacion1.jpg" %}" width=100%>
    </div>
    
    <br><br>
    <br><br>
    <div class="w-50 m-auto" style="background-color: hsl(0,0%,99%, 0.6)">
    <h1 class="text-center" style="color:black; padding-top:1em; font-family:san-serif">Los procesos de producción de café</h1>
    <p class="text-center" style="color:black; font-size:1.1em; padding-top:5em">El proceso de producción del café se caracteriza por un conjunto de etapas que consiguen obtener una de las bebidas más consumidas hoy en día.
     Se trata de un proceso complejo que requiere gran dedicación y experiencia para conseguir una calidad excepcional y sin igual.

    El proceso más común de producción suele dividirse en etapas diferentes que se inician con la obtención de frutos de cafeto,
     que es la planta de la que se obtiene esta infusión</p>
     <br>

     <h1 style="color:black; font-family:san-serif"> Etapa 1: Plantación</h1>
     <br><br>
     <p style="color:black; font-size:1.1em">Es la primera etapa y más importante para producir café, ya que marca el inicio del 
        ciclo que va de la siembra de la semilla hasta el crecimiento de la planta. Se puede realizar la plantación al sol 
        o a la sombra, en función de las necesidades. Una vez plantado el cafeto, deberemos esperar 
        entre 3 y 4 años para producir la primera cosecha. Posteriormente, cada planta vivirá aproximadamente 20 años.</p>
        <br><br>
     </div>

     <div class="row">

     <div  class="col-6" style="">
        <img src=" {% static "imagenes/plantacion3.jpg" %}" width=100%>
    </div>
    <div  class="col-6" style=" ">
        <img src=" {% static "imagenes/plantacion2.jpg" %}" width=100%>
    </div>
    </div>

    
    <h1 style="color:white; padding-top:1em; font-family:san-serif; ">Etapa 2:La cosecha de café</h1>
    <div class="row" style="background-color: hsl(0,0%,99%, 0.6)">
           
        <div class="col-6" style="padding-top:0.5em">
            <img src=" {% static "imagenes/cosecha.jpg" %}" width=100%>
        </div>
    
        <div class="col-6" style="background-color: hsl(0,0%,99%, 0.6)">
            
            <p style="color:black; font-size:1.1em">La cosecha del café se produce de forma anual cuando las cerezas del café alcanzan la maduración.
                Existen dos formas métodos para realizarla:
       
               Picking: es el proceso que se efectúa de forma manual y en plena fase de madurez,
                dejando aquellas plantas que aún se encuentran verdes.
                <br><br>
               Stripping: es el proceso que se efectúa de forma industrial, es decir, mecánica. 
               En este caso, las bayas que se recogen presentan diferentes grados de maduración, 
               por lo que se deberá efectuar una revisión posterior de aquellas que no han alcanzado la madurez</p>
          </div>
        </div>
        <br><br>
        <h1 class="text-center" style="color:white; padding-top:0.8em; font-family:san-serif">Etapa 3:Despulpado</h1>
        <div class="col-4" class="mx-auto w-10" >
            <img src=" {% static "imagenes/cosecha1.jpg" %}" width=100%>
        </div>
        <div class="col-4" class="mx-auto w-20" >
            <img src=" {% static "imagenes/lavado1.jpg" %}" width=100%>
        </div>
        <div class="col-4" class="mx-auto w-10" >
            <img src=" {% static "imagenes/lavado.jpg" %}" width=100%>
        </div>

        <div class="row" style="background-color: hsl(0,0%,99%, 0.6)">
        <div class="w-50 m-auto">        
        <p style="color:black; font-size:1.1em; padding-top:0.8em">
            Una vez terminada la cosecha, se secan los granos mediante una técnica húmeda o seca,
             en función del gusto que queramos obtener.
              Posteriormente, se eliminan todos los residuos y 
             se procede a quitar las capas que en vuelven los granos de café, para obtener el café limpio o verde. 
            Una vez finalizado el proceso, se clasifica el producto obtenido mediante diferentes criterios.</p>
            <br><br>

            <h1 style="color:black; font-family:san-serif">Etapa 4:Tueste</h1>
            <p class="text-center" style="color:black; font-size:1.1em; padding-top:0.8em">
                En esta fase, el producto adquiere el sabor y aroma por la que reconocemos nuestra taza de café, 
                mediante el procesamiento del grano en hornos. Gracias a ello, se consigue aumentar el tamaño del mismo,
                 reducir su cafeína, perder la humedad y adquirir el color tostado típico que caracteriza el café.</p>
            <br><br>

            <h1 style="color:black; font-family:san-serif">Etapa 5:Envase y comercialización</h1>
            <p class="text-center" style="color:black; font-size:1.1em; padding-top:0.8em">
Llegamos a la última etapa de la producción del café. Si se trata de café en grano o molido,
se puede comercializar directamente mediante una previa actuación del molinillo. 
Usualmente, esta etapa se realiza en el país de consumo del café, mediante un envase previo al vacío.</p>
<br><br>

<h1 style="color:black; font-family:san-serif">Etapa 6:Preparación del café</h1>
<p class="text-center" style="color:black; font-size:1.1em; padding-top:0.8em">Existen múltiples formas de poder preparar un buen café, en función del gusto del consumidor final. 
Encárgate de escoger la mejor cafetera para tu negocio o hogar y saborea las mejores recetas para 
disfrutar de esta particular y preciada infusión.
</p>
</div>
</div>

<div class="row" style="padding-top:1em">

<div class="col-4" class="mx-auto w-10" style="padding-top:0.8em">
    <img src=" {% static "cafe-15.jpg" %}" width=100%>
</div>
<div class="col-4" class="mx-auto w-20" >
    <img src=" {% static "imagenes/tostado1.jpg" %}" width=100%>
</div>
<div class="col-4" class="mx-auto w-10" >
    <img src=" {% static "imagenes/tostado2.jpg" %}" width=100%>
</div>
<div class="col-4" class="mx-auto w-10" >
    <img src=" {% static "imagenes/caficultor.jpg" %}" width=100%>
</div>
<div class="col-4" class="mx-auto w-20" >
    <img src=" {% static "imagenes/secado2.jpg" %}" width=100%>
</div>
<div class="col-4" class="mx-auto w-10" >
    <img src=" {% static "imagenes/secado4.jpg" %}" width=100%>
</div>
</div>

{% endblock content %}

barApp/templates/card.html
<div class="row my-4">
    {% for producto in product_food %}
    <div class="col-4 ">
    <div class="card my-3 mx-2" >
        <img src="{{producto.imagen_P.url}}" class="card-img-top" alt="">
        <div class="card-body">
            <h5 class="card-title">{{producto.nombre_P}}</h5>
            <p class="card-text">{{producto.descripcion_P}}</p>
            <p class="card-text text-end"><small class="text-muted">${{producto.precio_P}}</small></p>
        </div>
        <div class="card-footer text center">
            <a href="#" class="btn btn-success">Agregar</a>
        </div>
    </div>
    </div>
    {% endfor %}
    <p class="text-end"><a class="btn border border-ligth px-3" style=" color:white" href="{% url "food" %}"> Ver más </a></p>
</div>

barApp/templates/cold.html
{% extends 'body.html' %}
{% load static %}
{% block title %}Bebidas frías{% endblock title %}

{% block content %}



<div style="position:absolute; border:white 0.7px solid; padding-top: 0.8em; width:34%; left:33%; top:50%; z-index:100; font-family:san-serif">

  <h2 style="color:white; text-align:center; font-size:3.5em">Bebidas frías</h2>

</div>
<img src="{% static "imagenes/beers.jpg" %}" width="100%">
<div class="bg-image"></div>


<div style="position:absolute; top: 20%; left:10%; width:80%; border:1px dotted #0c0c0c; padding: 15em 30em; filter: blur(0.5px);
  -webkit-filter: blur(1px); background-color: rgba(0, 0, 0, 0.308);">
</div>



<div class="container">
    <div class="row my-4 ">
        {% for producto in productos %}
        <div class="col-4 ">
        <div class="card my-3 mx-2">
            <img src="{{ producto.imagen_P.url}}" class="card-img-top" alt="">
            <div class="card-body ">
                <h5 class="card-title">{{producto.nombre_P}}</h5>
                <p class="card-text">{{producto.descripcion_P}}</p>
                <p class="card-text text-end"><small class="text-muted">${{producto.precio_P}}</small></p>
            </div>
            <div class="card-footer text center">
              <a href=" {% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar</a>
          </div>
        </div>
        </div>
        {% endfor %} 
    </div>
</div>
    

{% endblock %}

barApp/templates/contacto.html
{% extends 'body.html' %}
{% load bootstrap5 %}
{% bootstrap_messages%}
{% load static %}
{% block title %}Contacto{% endblock title %}



{% block content %}
<h1 class="text-center" style="color:white"> Contacto </h1>
<div class="mx-auto w-50 " style="color:white"> 
    <form method="post" style="width:65%">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">Contacto</button>
    </form>
</div>


{% endblock %}

barApp/templates/food.html
{%  extends 'body.html' %}
{% load static %}
{% block title %} Alimentos {% endblock title %}


{% block content %}


<div style="position:absolute; border:white 0.7px solid; padding-top: 0.8em; width:34%; left:33%; top:50%; z-index:100; font-family:san-serif">

    <h2 style="color:white; text-align:center; font-size:3.5em">Alimentos</h2>
  
  </div>
  <img src="{% static "imagenes/food1.jpg" %}" width="100%">
  <div class="bg-image"></div>
  
  
  <div style="position:absolute; top: 20%; left:10%; width:80%; border:1px dotted #0c0c0c; padding: 15em 30em; filter: blur(0.5px);
    -webkit-filter: blur(1px); background-color: rgba(0, 0, 0, 0.5);">
  </div>
  

<div class="container">
    <div class="row my-4 ">
        {% for producto in productos %}
        <div class="col-4 ">
        <div class="card my-3 mx-2">
            <img src="{{ producto.imagen_P.url}}" class="card-img-top" alt="">
            <div class="card-body ">
                <h5 class="card-title">{{producto.nombre_P}}</h5>
                <p class="card-text">{{producto.descripcion_P}}</p>
                <p class="card-text text-end"><small class="text-muted">${{producto.precio_P}}</small></p>
            </div>
            <div class="card-footer text center">
                <a href=" {% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar</a>
            </div>
        </div>
        </div>
        {% endfor %} 
    </div>
</div>
    

{% endblock %}

barApp/templates/hot.html
{% extends 'body.html' %}
{% load static %} 
{% block title %}Bebidas calientes{% endblock title %}

{% block content %}


<div style="position:absolute; border:white 0.7px solid; padding-top: 0.8em; width:34%; left:33%; top:50%; z-index:100; font-family:san-serif">

    <h2 style="color:white; text-align:center; font-size:3.5em">Bebidas calientes</h2>
  
  </div>
  <img src="{% static "imagenes/cafe29.jpg" %}" width="100%">
  <div class="bg-image">
    
  </div>
  
  
  <div style="position:absolute; top: 20%; left:10%; width:80%; border:1px dotted #0c0c0c; padding: 15em 30em; filter: blur(0.5px);
    -webkit-filter: blur(1px); background-color: rgba(0, 0, 0, 0.308);">
  </div>
  

<div class="container">
    <div class="row my-4">
    {% for producto in productos %}
    <div class="col-4 ">
    <div class="card my-3 mx-2" >
        <img src="{{producto.imagen_P.url}}" class="card-img-top" alt="">
        <div class="card-body">
            <h5 class="card-title">{{producto.nombre_P}}</h5>
            <p class="card-text">{{producto.descripcion_P}}</p>
            <p class="card-text text-end"><small class="text-muted">${{producto.precio_P}}</small></p>
        </div>
        <div class="card-footer text center">
          <a href=" {% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar</a>
      </div>
    </div>
    </div>
    {% endfor %}
</div>
</div>
{% endblock content %}

barApp/templates/imagenes.html
numero+=10
[: numero]

barApp/templates/producto.html
{%  extends 'body.html' %}
{% load static %}
{% block title %} Productos{% endblock title %}

{% block content %}

<div class="row justify-content-center align-items-center" >
    <div class="col-5">
        <div class="align-middle mx-5">
            <h1 class="text-center mx-5" style="color:white">Productos</h1>
            <p class="text-center mx-5" style="color:white"> Acá encontrarás una selección de nuestros productos de Oh la lá 
                según las categorías disponibles.
            </P>
        </div>        
    </div>
    <div class="col-7">
        <img src=" {% static "imagenes/bebida.jpg"%}" width=100% >
    </div>
</div>
<div class="container">
    <h1 class="text-center mt-4" style="color:white">Bebidas frías</h1>
    <div class="row my-4">
        
    {% for producto in product_cold %}
    <div class="col-4 ">
    <div class="card my-3 mx-2" >
        <img src="{{producto.imagen_P.url}}" class="card-img-top" alt="">
        <div class="card-body">
            <h5 class="card-title">{{producto.nombre_P}}</h5>
            <p class="card-text">{{producto.descripcion_P}}</p>
            <p class="card-text text-end"><small class="text-muted">${{producto.precio_P}}</small></p>
        </div>
        <div class="card-footer text center">
            <a href=" {% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar</a>
        </div>
    </div>
    </div>
    {% endfor %}
    <p class="text-end"><a class="btn border border-ligth px-3" style=" color:white" href=" {% url "cold" %}" > Ver más </a></p>
</div>

<hr>

<h1 class="text-center mt-3" style="color:white">Bebidas calientes</h1>
    <div class="row my-4">
        <div class="container">"
            div style="float:right;"
            <p style="color: white;">Texto de prueba</p>
        </div>
    {% for producto in product_hot %}
    <div class="col-4 ">
    <div class="card my-3 mx-2" >
        <img src="{{producto.imagen_P.url}}" class="card-img-top" alt="">
        <div class="card-body">
            <h5 class="card-title">{{producto.nombre_P}}</h5>
            <p class="card-text">{{producto.descripcion_P}}</p>
            <p class="card-text text-end"><small class="text-muted">${{producto.precio_P}}</small></p>
        </div>
        <div class="card-footer text center">
            <a href="#" class="btn btn-success">Agregar</a>
        </div>
    </div>
    </div>
    {% endfor %}
    <p class="text-end"><a class="btn border border-ligth px-3" style=" color:white" href= "{% url "hot"%}">Ver más</a></p>
</div>

<hr>

<h1 class="text-center mt-3" style="color:white">Alimentos</h1>
    <div class="row my-4">
        <div class="container">"
            div style="float:right;"
            <p style="color: white;">Texto de prueba</p>
        </div>
    {% for producto in product_food %}
    <div class="col-4 ">
    <div class="card my-3 mx-2" >
        <img src="{{producto.imagen_P.url}}" class="card-img-top" alt="">
        <div class="card-body">
            <h5 class="card-title">{{producto.nombre_P}}</h5>
            <p class="card-text">{{producto.descripcion_P}}</p>
            <p class="card-text text-end"><small class="text-muted">${{producto.precio_P}}</small></p>
        </div>
        <div class="card-footer text center">
            <a href="#" class="btn btn-success">Agregar</a>
        </div>
    </div>
    </div>
    {% endfor %}
    <p class="text-end"><a class="btn border border-ligth px-3" style=" color:white" href="{% url "food" %}"> Ver más </a></p>
</div>
</div>

{% endblock content%}